services:
  php:
    container_name: moodlit_back_php
    restart: on-failure
    build: ./
    image: moodlit_back_php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./.docker/var/logs/apache/:/var/log/apache2:delegated
      - ./var/logs/php/:/var/log/php:delegated
    depends_on:
      - postgresdb
    command: >
      sh -c "wait-for-it postgresdb:5432 --
             php bin/console doctrine:database:create --if-not-exists &&
             php bin/console doctrine:schema:update --force &&
             apache2-foreground"

  postgresdb:
    container_name: moodlit_back_postgres
    restart: on-failure
    image: postgres:15
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Paris
