App\Entity\User:
  properties:
    email:
      - Email:
          message: The email is not valid
      - NotBlank: ~

    password:
      - NotBlank: ~
      - Length:
          min: 6
          minMessage: The password should be at least 6 characters

    name:
      - NotBlank: ~
      - Length:
          min: 3
          minMessage: The name should be at least 3 characters
      - Length:
          max: 12
          maxMessage: The name should not be longer than 12 characters